spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/product?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: product
server:
  port: 8400
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto