spring:
  cloud:
    gateway:
      routes:
        - id: product_route
          uri: lb://product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<seg>.*),/$\{seg}

        - id: ware_route
          uri: lb://ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<seg>.*),/$\{seg}

        - id: third_party_route
          uri: lb://third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<seg>.*),/$\{seg}

        - id: member_route
          uri: lb://member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<seg>.*),/$\{seg}
        # 其他api转发给renren-fast
        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<seg>.*),/renren-fast/$\{seg}
        # 域名配置
        - id: host_route
          uri: lb://product
          predicates:
            - Host=jmall.com
        - id: search_route
          uri: lb://search
          predicates:
            - Host=search.jmall.com
























